#!/bin/bash
echo -e "\e[0;34mque archivo quieres eliminar, con la extension\e[0m"
read archivo
echo -e "\e[0;34mque archivo quieres renombrar, con la extension\e[0m"
read renom
echo -e "\e[0;34mcual es la extension de tu archivo, con punto\e[0m"
read extension
echo -e "\e[0;34mque nombre le quieres poner a tu archivo, sin la extension\e[0m"
read nomb
nomb=$nomb
renom=$renom
extension=$extension
archivo=$archivo
if [ -f $archivo ]; then
rm $archivo
echo -e "\e[1;31meste archivo $archivo ya esta eliminado\e[0m"
if [ -f $renom ]; then
mv $renom $nomb$extension
echo -e "\e[1;31mel nombre de este archivo $renom se a cambiado a $nomb$extension\e[0m"
else
echo -e "\e[1;31creo que algo falla\e[0m"
fi
fi
