#!/bin/bash 
echo "que archivo quieres eliminar"
read archivo
archivo=$archivo
if [ -f $archivo ]; then 
rm $archivo
echo "este archivo $archivo ya esta eliminado"
else 
echo "este archivo $archivo no existe"
fi
