#!/bin/bash 
opcion=0
menu() {
echo -e "\e[0;34m1. eliminar\e[0m"
echo -e "\e[0;34m2. renombrar\e[0m"
echo -e "\e[0;34m3. buscar\e[0m"
}
eliminar() {
echo -e "\e[0;34mque archivo quieres eliminar, con la extension\e[0m"
read archivo
archivo=$archivo
if [ -f $archivo ]; then
rm $archivo
echo -e "\e[1;31meste archivo $archivo ya esta eliminado\e[0m"
else 
echo -e "\e[1;31creo que algo falla\e[0m"
fi
}
renombrar() {
echo -e "\e[0;34mque archivo quieres renombrar, con la extension\e[0m"
read renom
echo -e "\e[0;34mcual es la extension de tu archivo, con punto\e[0m"
read extension
echo -e "\e[0;34mque nombre le quieres poner a tu archivo, sin la extension\e[0"
read nomb
renom$renom
extension=$extension
nomb=$nomb
if [ -f $renom ]; then
mv $renom $nomb$extension
root=$(pwd)/$ubicacion
echo -e "\e[1;31mel nombre de este archivo $renom se a cambiado a $nomb$extensi y esta ubicado en: $root"
else
echo -e "\e[1;31creo que algo falla\e[0m"
fi
}
buscar(){
echo -e "\e[0;34mque archivo quieres buscar\e[0m"
read archivo
archivo=$archivo
if [ -f $archivo ]; then
busca=$(pwd)/$archivo
echo -e "\e[1;31mel archivo $archivo esta en: $busca\e[0m"
else
echo -e "\e[1;31creo que algo falla\e[0m" 
fi
}
while true; do
menu
echo -e "\e[1;31mquieres eliminar o renombrar un archivo\e[0m"
read opcion
case $opcion in
1) eliminar ;;
2) renombrar ;;
3) buscar ;;
*) echo -e "\e[0;34mopcion invalida\e[0m" ;;
esac 
done
