#!/bin/bash 
echo "pon tres numeros"
read n1 
read n2 
read n3 
n1=$n1
n2=$n2
n3=$n3
if [ "$n1" -gt "$n2" ] && [ "$n1" -gt "$n3" ]; then
echo "el numero $n1 es el mayor"
fi
if [ "$n2" -gt "$n1" ] && [ "$n2" -gt "$n3" ]; then
echo "el numero $n2 es el mayor"
fi 
if [ "$n3" -gt "$n1" ] && [ "$n3" -gt "$n2" ]; then
echo "el numero $n3 es el mayor"
fi
